# EDA — Rentabilidades

Explore raw SP rentabilidades files before writing the cleaner.

**Goal:** understand the exact structure (sheet names, header rows, column names, data types) so we can write `clean_rentabilidades.py` correctly.

In [8]:

# importing the necesary things
import sys
sys.path.insert(0, "..")

from etl.scrape_rentabilidades import run
from etl.config import RENT_URL, RENT_FORM_BASE

In [9]:
# fetch the data 'rentabilidad' from spensiones

run()

In [3]:

# read parquet

import pandas as pd

df = pd.read_parquet("../data/raw/rentabilidades/rentabilidades_raw.parquet")

display(df[(df['year'] == 2026) & (df['afp'] == 'Capital') &(df['fondo'] == 'A')])

          afp  rent_real fondo  year  month
8630  Capital       1.12     A  2026      1
8670  Capital       2.07     A  2026      2
8710  Capital      -2.95     A  2026      3
8750  Capital        NaN     A  2026      4

In [ ]:
# RENTABILIDAD ANUALIZADA

df_2019 = df[(df['year'] == 2019) & (df['afp'] == 'Cuprum') &(df['fondo'] == 'A')]

def compound_compute(monthly_returns: pd.Series) -> float | None:
    total_return = 1
    for monthly_return in monthly_returns:
        total_return = total_return * (1 + (monthly_return / 100))
    total_return = (total_return - 1) * 100
    return total_return

anual_return = df.groupby(['afp','fondo','year']).agg(anual_return = ('rent_real',compound_compute)).reset_index()

anual_return.tail(20)


anual_return[(anual_return['fondo'] == 'C')]

           afp fondo  year  anual_return
6    Bansander     C  2006     15.912660
7    Bansander     C  2007      4.820956
8    Bansander     C  2008     -4.281137
53     Capital     C  2008    -15.706530
54     Capital     C  2009     21.833128
..         ...   ...   ...           ...
754        Uno     C  2022    -10.110629
755        Uno     C  2023      3.281675
756        Uno     C  2024      3.466088
757        Uno     C  2025     12.354474
758        Uno     C  2026           NaN

[155 rows x 4 columns]

: